name: Hello mateen
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: build steps
        run: echo "mateen's build"
  test:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: testing phase
         run: echo "mateen's running test cases"
  deploy:
     runs-on: ubuntu-latest
     needs: test
     steps:
       - name: deploying phase
         run: echo "mateen's deploying the app"
         
          
